#ifndef TASKS_COMMON_H_
#define TASKS_COMMON_H_

#define OBD_TASK_STACK_SIZE 4096
#define OBD_TASK_PRIORITY   5
#define OBD_TASK_CORE_ID    1

#define HTTP_SERVER_TASK_STACK_SIZE 4096
#define HTTP_SERVER_TASK_PRIORITY   4
#define HTTP_SERVER_TASK_CORE_ID    0

#endif