M48
; DRILL file {KiCad 7.0.11} date Sun Feb  2 20:15:24 2025
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-02-02T20:15:24+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0374
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X3.7261Y-5.82
X3.9939Y-5.82
T2
X1.105Y-4.14
X1.585Y-5.405
X4.985Y-4.14
X4.985Y-5.86
M30
